project_name: "natera_recombination_gwas"
metadata: "../../data/spectrum_metadata_merged.csv"
datadir: "/data/rmccoy22/natera_spectrum/genotypes/imputed_parents_031423/"
phenotypes:
  - "mean_co_per_chrom"
  - "var_co_per_chrom"
methods:
  - "plink2"
  - "regenie"
