project_name: "natera_recombination_gwas"
metadata: "../../data/spectrum_metadata_merged.csv"
crossovers: "../co_post_process/results/v30b_heuristic_90_nsib.crossover_filt.euploid_only.tsv.gz"
recomb_map: "../../data/genmaps/halldorsson19/aau1043_datas3.gz"
hotspots:
    Male: "../../data/genmaps/halldorsson19/aau1043_datas1.gz"
    Female: "../../data/genmaps/halldorsson19/aau1043_datas2.gz"
bed_files:
    centromeres: "../../data/gaps/centromeres_grch38.bed"
    telomeres: "../../data/gaps/telomeres_grch38.bed"
    pratto2014: "../../data/gaps/pratto2014_dmc1_hotspots.hg38.tsv"
datadir: "/data/rmccoy22/natera_spectrum/genotypes/imputed_parents_100423/"
methods:
  - "plink2"
  - "regenie"
