metadata: "../../data/spectrum_metadata_merged.csv"
aneuploidy_data: "/data/rmccoy22/natera_spectrum/karyohmm_outputs/compiled_output/natera_embryos.karyohmm_v30a.bph_sph_trisomy.full_annotation.031624.tsv.gz"
crossover_data: 
    v30b_heuristic_90_nsib_qual: 
      crossover_calls: '../crossovers/results/test_crossover_heuristic.v30b.nsib_support.geno_qual.tsv.gz'
      qual_thresh: 0.90
    v30b_heuristic_95_nsib_qual: 
      crossover_calls: '../crossovers/results/test_crossover_heuristic.v30b.nsib_support.geno_qual.tsv.gz'
      qual_thresh: 0.95
covariates: '../gwas/results/covariates/natera_recombination_gwas.covars.regenie.txt'
recomb_maps:
  deCode_haldorsson19: "../../data/genmaps/halldorsson19/aau1043_datas3.gz"
hotspots:
    Male: "../../data/genmaps/halldorsson19/aau1043_datas1.gz"
    Female: "../../data/genmaps/halldorsson19/aau1043_datas2.gz"
centromeres: "../../data/gaps/centromeres_grch38.bed"
telomeres: "../../data/gaps/telomeres_grch38.bed"
chromsize: "../../data/gaps/hg38.chrom.sizes"
