metadata: "../../data/spectrum_metadata_merged.csv"
aneuploidy_data: "/data/rmccoy22/natera_spectrum/karyohmm_outputs/compiled_output/natera_embryos.karyohmm_v30a.bph_sph_trisomy.full_annotation.031624.tsv.gz"
crossover_data: 
    v30b_heuristic_90_nsib_qual: '../crossovers/results/test_crossover_heuristic.v30b.nsib_support.geno_qual.tsv.gz'
recomb_maps:
  deCode_haldorsson19: "../../data/genmaps/halldorsson19/aau1043_datas3.gz"
